version: 2.1

orbs:
  gh: circleci/github-cli@2.1.0
  sre: tracktor/ci-tools@0.8.17

references:
  production_context: &production_context
    - npm
    - github
  filters_not_tagged: &filters_not_tagged
    tags:
      ignore: /.*/
  only_master: &only_master
    tags:
      ignore: /.*/
    branches:
      only: /^master$/
  filters_only_tags: &filters_only_tags
    tags:
      only: /.*/
    branches:
      ignore: /.*/

executors:
  default:
    docker:
      - image: cimg/node:22.15.1

jobs:
  bump-version:
    executor: default
    steps:
      - gh/setup
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}
      - add_ssh_keys:
          fingerprints:
            - "66:22:37:b5:81:f7:c2:63:3e:98:7b:a3:88:16:75:93"
      - sre/bump-version:
          lang: "js"
          branch: "master"
  run-unit-tests:
    executor: default
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}
      - run:
          name: Yarn install
          command: yarn
      - run:
          command: yarn run test
      - save_cache:
          key: dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
  publish-npm:
    executor: default
    steps:
      - gh/setup
      - checkout
      - run:
          name: Yarn install
          command: yarn
      - run:
          name: publish on npm
          command: yarn publish --access public

workflows:
  Run Tests:
    jobs:
      - run-unit-tests:
          filters: *filters_not_tagged
          name: Run unit tests
      - bump-version:
          filters: *only_master
          context: *production_context
          requires:
            - Run unit tests
  Publish:
    jobs:
      - publish-npm:
          context: *production_context
          filters: *filters_only_tags
